[fix] Config Applied checks would be skipped when device config status is errored #195
openwisp/openwisp-monitoring pull request #235
Opened 2020-09-23 13:13 UTC by nepython

Closes #195
This should be now taken care off by openwisp-controller (https://github.com/openwisp/openwisp-controller/pull/265).

Checks:

- [x] I have manually tested the proposed changes
- [x] I have written new test cases to avoid regressions (if necessary)
- [ ] ~I have updated the documentation (e.g. README.rst)~

2020-09-24 04:11 UTC, nemesisdesign requested changes
Welcome back! See my comment below.

2020-09-24 04:11 UTC, nemesisdesign commented on openwisp_monitoring/check/tests/test_models.py
> +        self.assertIsNone(check.perform_check())
This test passes also without the fix above. Try it.
I just tried it and it's not failing.

You must always ensure the test fails without your patch.
The best thing is to add the test before the fix, alternatively comment out the fix temporarily.

2020-09-24 17:12 UTC, nemesisdesign reviewed
I realized something. We'll end up with the health status being OK when what we want in the truth is to avoid the redundant alert.

I'm thinking if we can get the status change without the alert.

That would be the ideal solution. This way we would have the notification from openwisp-controller, but the health status would change to PROBLEM instead of remaining OK.

A simple approach which doesn't require changing a lot of other models would be something like:

```python
# if the device is down or does not have a config
# do not run config applied check
if (
    self.related_object.monitoring.status in ['critical', 'unknown']
    or not hasattr(self.related_object, 'config')
):
    return

metric = self._get_metric()
result = int(self.related_object.config.status == 'applied')

# if the device config is in error status we don't need to notify
# the user (because that's already done by openwisp-controller)
# but we need to ensure health status will be changed
if self.related_object.config.status == 'error':
    store = False
    metric.check_threshold(notify=False)

if store:
    metric.write(
        result, retention_policy=SHORT_RP,
    )
return result
```

This would require adding a `notify` argument to the `check_threshold`.

alternatively, we could add the `notify` argument also to metric.write() which wouold in turn pass it to `check_threshold`, the resulting code would then be simpler:

```python
# if the device is down or does not have a config
# do not run config applied check
if (
    self.related_object.monitoring.status in ['critical', 'unknown']
    or not hasattr(self.related_object, 'config')
):
    return

metric = self._get_metric()
result = int(self.related_object.config.status == 'applied')

# if the device config is in error status we don't need to notify
# the user (because that's already done by openwisp-controller)
# but we need to ensure health status will be changed
notify = self.related_object.config.status != 'error':

if store:
    metric.write(
        result, retention_policy=SHORT_RP,
    )

return result
```

This may also have the additional benefit that we will be notified when the configuration goes back to normal! Which is really nice, we don't have this in openwisp-controller, so the two would complement each other.

I'm in favour of the second approach, what do you think?

2020-09-24 18:39 UTC, nepython commented
Yes, the second approach seems more convenient as it would provide us with more flexibility with (when to and when not to send) alerts (neglecting the threshold if need be like here) during a metric write in the longer run. I will work upon it :)

2020-09-25 20:09 UTC, nepython commented on openwisp_monitoring/monitoring/base/models.py
> +    def check_threshold(self, value, time=None, retention_policy=None, send_alert=True):
named this parameter as `send_alert` instead of `notify` to avoid any confusion with a signal of the same name.

2020-09-30 03:03 UTC, nemesisdesign approved these changes
Tested it and it works, great work @nepython :+1:

2020-09-30 03:25 UTC, merged