[fix] Removed 'openwisp_monitoring.notifications' from installed_apps
openwisp/openwisp-monitoring pull request #250
Opened 2020-11-13 11:30 UTC by devkapilbansal

Closes #233

Checks:

- [ ] I have manually tested the proposed changes
- [ ] I have written new test cases to avoid regressions (if necessary)

2020-11-13 20:07 UTC, devkapilbansal commented
> @devkapilbansal please avoid changing lines that are not related to the fix because it makes tracking changes to the code harder.

Okay I should make those changes in a separate commit

2020-11-15 12:36 UTC, pandafy requested changes
@devkapilbansal create individual PRs for these commits. This PR has changes in 60 different files which makes it a bit difficult to review. Moreover, I don't see these commits related to each other in any way. 

From [OpenWISP's contribution guidelines](https://openwisp.io/docs/developer/contributing.html)
> make sure to send one pull request for each feature. Each feature should contain one commit. If you make multiple commits for a single feature/bug-fix, squash them to a single commit providing an informative commit message after you are done with the required changes.
in case of big features in which multiple related features/changes needs to be implemented, multiple commits (one commit per feature) in a single PR can be accepted.

2020-11-15 12:40 UTC, devkapilbansal commented
@pandafy breaking them in two generates formatting error in both

2020-11-15 12:44 UTC, pandafy commented
@devkapilbansal I don't see how #182 and #233 are related?

2020-11-19 20:52 UTC, pandafy reviewed
@devkapilbansal you will need to remove files in `openwisp_monitoring/notifications` as well.

2020-12-10 00:57 UTC, nemesisdesign commented
@devkapilbansal what's up with this one? Did you forget about it?

2020-12-10 22:08 UTC, devkapilbansal commented
@nemesisdesign updated. The Travis checks are failing because on formatting issues that I already included in #251

2020-12-10 22:27 UTC, nemesisdesign commented
> @nemesisdesign updated. The Travis checks are failing because on formatting issues that I already included in #251

@devkapilbansal then the correct way of doing it is to rebase this PR on the latest master, please do so.

2020-12-10 22:37 UTC, nemesisdesign requested changes
> > @nemesisdesign updated. The Travis checks are failing because on formatting issues that I already included in #251
> 
> @devkapilbansal then the correct way of doing it is to rebase this PR on the latest master, please do so.

2020-12-15 23:42 UTC, nemesisdesign approved these changes

2020-12-15 23:42 UTC, merged