[admin] Added monitoring status graph on dashboard
openwisp/openwisp-monitoring pull request #264
Opened 2021-01-18 06:11 UTC by pandafy

Checks:

- [x] I have manually tested the proposed changes
- [ ] I have written new test cases to avoid regressions (if necessary)
- [ ] ~I have updated the documentation (e.g. README.rst)~

--------
![image](https://user-images.githubusercontent.com/32094433/104878339-c07cf500-5981-11eb-8010-92c3ed000c93.png)
--------

Along with https://github.com/openwisp/openwisp-controller/pull/369, it looks like below 
![Screenshot from 2021-01-16 17-17-57](https://user-images.githubusercontent.com/32094433/104878415-ea361c00-5981-11eb-9cbc-c4337fa4e510.png)

--------

**Blockers**:

- [ ] https://github.com/openwisp/openwisp-utils/pull/168
- [ ] https://github.com/openwisp/openwisp-controller/pull/369

2021-01-20 03:33 UTC, nemesisdesign reviewed
This is what I see:

![Screenshot from 2021-01-19 22-31-37](https://user-images.githubusercontent.com/841044/105123477-24004300-5aa6-11eb-8954-90ab15797a9e.png)

The labels of the monitoring status looks cut.

2021-01-20 11:10 UTC, pandafy commented
@nemesisdesign  I spent some time trying to debug this but couldn't find the reason why this was happening. I noticed that it only happened in Chromium when testing with responsive toolbar. I tested it with different view port size by resizing the browser window and it worked fine. 

It also worked fine when tested with responsive toolbar of Firefox.

Were you testing it in responsive toolbar of Chrome or Chromium?  

I saw [many posts on the community forum of plotly](https://community.plotly.com/search?q=legend%20truncated) complaining about the same issue with horizontal legend. If you are facing this problem in normal browser view then we might have to switch to vertical legend.

2021-01-21 02:00 UTC, nemesisdesign commented
> @nemesisdesign I spent some time trying to debug this but couldn't find the reason why this was happening. I noticed that it only happened in Chromium when testing with responsive toolbar. I tested it with different view port size by resizing the browser window and it worked fine.
> 
> It also worked fine when tested with responsive toolbar of Firefox.
> 
> Were you testing it in responsive toolbar of Chrome or Chromium?
> 
> I saw [many posts on the community forum of plotly](https://community.plotly.com/search?q=legend%20truncated) complaining about the same issue with horizontal legend. If you are facing this problem in normal browser view then we might have to switch to vertical legend.

I tested 

> @nemesisdesign I spent some time trying to debug this but couldn't find the reason why this was happening. I noticed that it only happened in Chromium when testing with responsive toolbar. I tested it with different view port size by resizing the browser window and it worked fine.
> 
> It also worked fine when tested with responsive toolbar of Firefox.
> 
> Were you testing it in responsive toolbar of Chrome or Chromium?
> 
> I saw [many posts on the community forum of plotly](https://community.plotly.com/search?q=legend%20truncated) complaining about the same issue with horizontal legend. If you are facing this problem in normal browser view then we might have to switch to vertical legend.

It happens also on Firefox to me. It happens only in the monitoring pie chart, not in the controller chart.

2021-01-21 17:32 UTC, pandafy commented
![image](https://user-images.githubusercontent.com/32094433/105388257-71aeb400-5c3c-11eb-87b8-07d094dcc193.png)

I have updated the orientation of the legend to vertical instead of horizontal

@nemesisdesign where to define custom dependencies, since `./install-dev.sh` is not present anymore.

2021-01-25 01:55 UTC, nemesisdesign commented
> ![image](https://user-images.githubusercontent.com/32094433/105388257-71aeb400-5c3c-11eb-87b8-07d094dcc193.png)
> 
> I have updated the orientation of the legend to vertical instead of horizontal

Thx, will review and test asap.

> @nemesisdesign where to define custom dependencies, since `./install-dev.sh` is not present anymore.

I recently (finally!) found a better way of managing these dev dependencies, see:
https://github.com/openwisp/openwisp-radius/blob/d11d8bdba0e1519697cd78b5aa97a42f6aca79ac/requirements.txt#L7-L9

Use this method from now in all the repos please, for more info see [PEP 508](https://www.python.org/dev/peps/pep-0508/).

2021-01-28 03:06 UTC, nemesisdesign requested changes

2021-01-28 03:06 UTC, nemesisdesign commented on openwisp_monitoring/monitoring/apps.py
> +        register_dashboard_element(
this code should go in `openwisp_monitoring.device.apps`

2021-01-28 20:03 UTC, pandafy commented
I can't understand the reason why pip is not installing the latest version of openwisp-utils. I even enable `-I` in the installation command to ignore installed packages, but it has no effect. I will get back to it tomorrow.

2021-03-10 23:28 UTC, nemesisdesign commented on openwisp_monitoring/device/api/views.py
> +    # def get(self, *args, **kwargs):
TODO: remove this

2021-03-10 23:28 UTC, nemesisdesign commented on openwisp_monitoring/device/static/monitoring/js/device-map.js
> +      alert('Error while retrieving data');
TODO: use `gettext()` here

2021-03-10 23:28 UTC, nemesisdesign commented on openwisp_monitoring/device/tests/test_api.py
> +        # Location()
TODO add basic API tests

2021-03-10 23:28 UTC, nemesisdesign commented on tests/openwisp2/settings.py
> +OPENWISP_ADMIN_DASHBOARD_ENABLED = True
TODO: remove this, shouldn't be needed

2021-03-19 00:51 UTC, nemesisdesign commented
This is how it looks:

![dashboard1](https://user-images.githubusercontent.com/841044/111716062-3f2bcc80-8823-11eb-8719-119c38dbfce2.png)

2021-03-19 00:51 UTC, nemesisdesign commented
![dashboard2](https://user-images.githubusercontent.com/841044/111716121-5b2f6e00-8823-11eb-80ee-056a23ced357.png)

2021-03-19 01:22 UTC, merged