[change] Updated the serializers imports #287
openwisp/openwisp-monitoring pull request #288
Opened 2021-04-04 07:27 UTC by ManishShah120

closes #287

Checks:

- [x] I have manually tested the proposed changes
- [ ] I have written new test cases to avoid regressions (if necessary)
- [ ] I have updated the documentation (e.g. README.rst)

2021-04-04 16:50 UTC, nemesisdesign requested changes
@ManishShah120 also here there are some serializers mixed with views, can you fix it please?
Also point the requirements.txt to the branch where you did the change so the build should pass.

2021-04-04 16:52 UTC, ManishShah120 commented
Sure will do it.

2021-04-04 20:11 UTC, ManishShah120 commented
Done @nemesisdesign

2021-04-06 02:20 UTC, nemesisdesign requested changes
Thanks @ManishShah120, please see my comment below and then we can merge!

2021-04-06 02:20 UTC, nemesisdesign commented on requirements.txt
> +openwisp-controller @ https://github.com/ManishShah120/openwisp-controller/tarball/issues/414-separate-serializer-classes
I just merged https://github.com/openwisp/openwisp-controller/pull/416, now we can switch this to master

2021-04-06 02:31 UTC, nemesisdesign approved these changes
I resolved the pending issue since I could do it easily, thanks @ManishShah120 :+1:

2021-04-06 02:32 UTC, merged