[feature] Added monitoring of WiFi Client and Sessions #360
openwisp/openwisp-monitoring pull request #372
Opened 2022-05-10 17:33 UTC by pandafy

Closes #360

TODO

- [ ]  Add documentation 

![Screenshot from 2022-05-10 22-49-12](https://user-images.githubusercontent.com/32094433/167688429-9cb79aba-d168-487d-9baa-06970f5bca28.png)
![Screenshot from 2022-05-10 22-45-38](https://user-images.githubusercontent.com/32094433/167688437-eb250489-96dc-47b8-a01e-ecc477d6d29f.png)

2022-05-11 17:08 UTC, nemesisdesign requested changes
First round of testing, looks very good! :+1: 

Let's add a wifi icon to openwisp-utils for the menu, I think you can move the menu up before metrics and charts (which aren't really useful for every day users).

I think we also need to add permissions to operators and administratrors to view wifi client and session objects.

See also my comments below.

2022-05-11 18:01 UTC, pandafy commented on openwisp_monitoring/monitoring/tasks.py
> +def delete_wifi_clients_and_session(days=6 * 30):
I planned to document it like https://github.com/openwisp/openwisp-notifications#scheduled-deletion-of-notifications

2022-05-13 19:10 UTC, nemesisdesign requested changes
Great progress Gagan!

Let's not forget the WiFi icon in the menu please.

See my comments below.

2022-05-13 19:10 UTC, nemesisdesign commented on README.rst
> +  along with other information.
The other points don't have a final dot so let's maintain consistency.

Let's make clear that both currently open sessions and past sessions can be viewed and filtered.

2022-05-13 19:22 UTC, nemesisdesign reviewed
The open wifi sessions button looks a bit too far, I tried giving it:

```
    position: relative;
    top: -20px;
```

And it's better, I think we should add the possibility of providing a CSS class here.

2022-05-14 00:02 UTC, nemesisdesign reviewed
I found a flaw in my design! If the de device is offline, the wifi clients remain online.
I think we should trigger the celery task when the device status moves into critical to close all the sessions

2022-05-17 17:31 UTC, nemesisdesign requested changes

2022-05-17 17:36 UTC, nemesisdesign requested changes

2022-05-17 17:36 UTC, nemesisdesign commented on openwisp_monitoring/device/migrations/0004_wificlient_wifisession.py
> +            assign_permissions_to_groups, reverse_code=migrations.RunPython.noop
please run this migration in a separate data migration step (file), do you remember on postgres we get errors when we try to do changes to the data in the same transaction in which the schema is changed? Please don't forget.. we already ran into this issue.

2022-05-17 18:39 UTC, nemesisdesign requested changes
we need to switch the openwisp-utils version to point to the current master for the wifi icon to work

2022-05-17 18:55 UTC, nemesisdesign approved these changes
Great :+1:

2022-05-17 19:00 UTC, merged