[feature] Added inline for WifiSession in DeviceAdmin #362
openwisp/openwisp-monitoring pull request #375
Opened 2022-05-18 11:21 UTC by pandafy

Closes #362

Checks:

- [x] I have manually tested the proposed changes
- [ ] I have written new test cases to avoid regressions (if necessary)
- [x] I have updated the documentation (e.g. README.rst)

2022-05-18 11:27 UTC, pandafy commented
@nemesisdesign I added the button inside the "WiFi Sessions" tab instead of adding it at the top along with other buttons ("Silence Notification", "Send Command", etc.) because those buttons perform operations directly related to the device. Also, it will become crowded if we keep adding buttons on the top. 

If you prefer, we can move this button to the top.

2022-05-18 21:09 UTC, nemesisdesign requested changes
I merged the latest master and fixed the tests, I did also some minor improvements.

Other problems found during testing pending solution:

- the see wifi sessions button is shown also in the other tabular inlines

I also found out https://github.com/openwisp/openwisp-monitoring/issues/378, but it's not directly caused by this PR but was introduced in the previous one.

2022-05-19 20:11 UTC, nemesisdesign approved these changes

2022-05-19 20:29 UTC, nemesisdesign approved these changes

2022-05-19 20:31 UTC, merged