[fix] Fixed WifiSession dashboard pie chart
openwisp/openwisp-monitoring pull request #438
Opened 2022-09-20 12:17 UTC by pandafy

The WifiSession pie chart on the dashboard was not filtering the
queryset by the related device's organization.

**Blockers**

- [ ] https://github.com/openwisp/openwisp-utils/pull/313

Checks:

- [x] I have manually tested the proposed changes
- [ ] I have written new test cases to avoid regressions (if necessary)
- [ ] I have updated the documentation (e.g. README.rst)

2022-09-20 12:17 UTC, pandafy commented on requirements-test.txt
> +openwisp-utils[qa] @ https://github.com/openwisp/openwisp-utils/tarball/62c6dfac559e914e8186de4aa80c56b03012ba38
TODO: Update this before merging!

2022-09-20 12:17 UTC, pandafy commented on requirements.txt
> +openwisp-utils[rest] @ https://github.com/openwisp/openwisp-utils/tarball/62c6dfac559e914e8186de4aa80c56b03012ba38
TODO: Update this before merging!

2022-09-25 14:23 UTC, nemesisdesign requested changes

2022-09-25 14:23 UTC, nemesisdesign commented on requirements-test.txt
> +openwisp-utils[qa] @ https://github.com/openwisp/openwisp-utils/tarball/62c6dfac559e914e8186de4aa80c56b03012ba38
```suggestion
openwisp-utils[qa] @ https://github.com/openwisp/openwisp-utils/tarball/5a8f1dea187586d85c77b46e6e3fd725f557e3c6
```

2022-09-25 14:23 UTC, nemesisdesign commented on requirements.txt
> +openwisp-utils[rest] @ https://github.com/openwisp/openwisp-utils/tarball/62c6dfac559e914e8186de4aa80c56b03012ba38
```suggestion
openwisp-utils[rest] @ https://github.com/openwisp/openwisp-utils/tarball/5a8f1dea187586d85c77b46e6e3fd725f557e3c6
```

2022-09-26 15:47 UTC, nemesisdesign approved these changes

2022-09-26 15:47 UTC, merged