[monitoring] Adding influxDB 2.x version support #274
openwisp/openwisp-monitoring pull request #584
Opened 2024-05-31 17:06 UTC by praptisharma28

Fixes #274

Checks:

- [ ] I have manually tested the proposed changes
- [ ] I have written new test cases to avoid regressions (if necessary)
- [ ] I have updated the documentation (e.g. README.rst)

2024-06-11 12:32 UTC, pandafy commented on openwisp_monitoring/db/backends/__init__.py
> +    timeseries_db = load_backend_module(module='client').DatabaseClient()
Any backend specific configuration should be done in the backend class. Perform this operation in the `__init__` method of the backend class 

```
.DatabaseClient(
        bucket=TIMESERIES_DB['BUCKET'],
        org=TIMESERIES_DB['ORG'],
        token=TIMESERIES_DB['TOKEN'],
        url=f"http://{TIMESERIES_DB['HOST']}:{TIMESERIES_DB['PORT']}",
 ```

2024-06-18 16:11 UTC, praptisharma28 commented
June 18th weekly call summary:
- Need to get ping check in influxdb 2.0 at the server locally, so that health status like "CRITICAL", "OK" are visible too and not just "UNKNOWN".
- Need to get charts which right now says an error when I check for charts.
Note:  Celery beat and worker will be running all the time along with the server, when I am working on 8000 port locally.

2024-06-25 17:31 UTC, nemesifier requested changes
There's too many `if` statements in the code (eg: if influxdb1 or influxdb2).
This is not the way to go. The logic for influxdb1 or influxdb2 must be encapsulated in each respective timeseries DB backend, the rest of the code should just be adapted to call that logic.

Please have a look at the work which was done for the elasticsearch backend to get an idea:
https://github.com/openwisp/openwisp-monitoring/pull/164

2024-07-01 13:15 UTC, pandafy requested changes
In our call today, @praptisharma28 walked me through the code and helped me understand the changes. In this process, we found some areas for improvement.

2024-07-01 13:15 UTC, pandafy commented on openwisp_monitoring/db/backends/influxdb2/client.py
> +        return query
Please move this query to queries.py and use `get_query()` method to generate the final query.

2024-07-01 17:25 UTC, praptisharma28 commented on openwisp_monitoring/monitoring/base/models.py
> +            'field_name': fields or self.config_dict.get('field_name'),
I used pdb, got:
```
(Pdb) params
{'field_name': None, 'key': 'test_metric', 'time': '2024-06-25', 'days': '7d', 'content_type': 'openwisp_users.user', 'object_id': '4f5f77d3-3b30-4eca-97c6-1301217a4edc', 'start_date': None, 'end_date': None, 'measurement': 'test_metric'}
```
But if I remove it, I lose on the summary of ```uptime``` chart. Charts like ```mostly reachable, unreachable, partially reachable``` are lost.

2024-07-02 11:23 UTC, pandafy commented on openwisp_monitoring/monitoring/base/models.py
> +            'field_name': fields or self.config_dict.get('field_name'),
![Screenshot from 2024-07-02 16-53-14](https://github.com/openwisp/openwisp-monitoring/assets/32094433/2764e3a7-f992-473e-a6f1-a967f41a272e)


There should be only one summary in the uptime chart.

2024-07-04 11:50 UTC, pandafy commented on openwisp_monitoring/db/backends/influxdb2/client.py
> +        flux_query = f'from(bucket:"{bucket}")'
@praptisharma28 why are you building the query like this here? Why aren't you using the queries defined in queries.py? 

This looks wrong. Charts for different metrics are handled differently. That's why there are individual queries for each chart.

2024-07-04 11:56 UTC, pandafy commented on openwisp_monitoring/db/backends/influxdb2/client.py
> +        flux_query = f'from(bucket:"{bucket}")'
My bad, I got confused between the  `get_list_queries` and `read` method. The current implementation is okay.

2026-04-01 18:54 UTC, pushpitkamboj commented
Hi, i was going through previous GSOC projects and saw someone did worked on this same gsoc project 2 years ago, was not completed? How much of the project was completed back then?
getting context from this feels relevant for gsoc'26 monitoring project
@pandafy @nemesifier

2026-07-29 19:26 UTC, closed without merging