[feature] Added check for WiFi Clients
openwisp/openwisp-monitoring pull request #623
Opened 2024-12-11 18:26 UTC by pandafy

## Checklist

- [x] I have read the [OpenWISP Contributing Guidelines](http://openwisp.io/docs/developer/contributing.html).
- [x] I have manually tested the changes proposed in this pull request.
- [x] I have written new test cases for new code and/or updated existing tests for changes to existing code.
- [x] I have updated the documentation.

## Description of Changes

- An alert is sent when the connected clients are less than configured threshold 
- An alert is sent when the connected clients are more than configured threshold

2025-01-02 19:37 UTC, nemesifier requested changes
The ordering in the alert settings tab seems alphabetical, so calling the two checks Max WiFi Clients and Min WiFi Clients causes the memory check to sit in between, which is bad ux. I think we should rename these to "WiFi Clients (Maximum)" and "WiFi Clients (Minimum)".

2025-01-02 19:37 UTC, nemesifier commented on docs/user/checks.rst
> +WiFi Client
```suggestion
WiFi Clients (Maximum & Minimum)
```

2025-01-02 19:37 UTC, nemesifier commented on docs/user/checks.rst
> +- **Maximum WiFi Users**: When the total number of WiFi clients connected
```suggestion
- **Maximum WiFi Clients**: When the total number of WiFi clients connected
```

I recommend consistency with the wording to avoid confusing readers.

2025-01-02 19:37 UTC, nemesifier commented on docs/user/checks.rst
> +- **Minimum WiFi Users**: When the total number of WiFi clients connected
```suggestion
- **Minimum WiFi Clients**: When the total number of WiFi clients connected
```

Same here.

2025-01-02 19:37 UTC, nemesifier commented on openwisp_monitoring/check/settings.py
> +        ('openwisp_monitoring.check.classes.WifiClient', 'Wifi Client'),
```suggestion
        ('openwisp_monitoring.check.classes.WifiClients', 'Wifi Clients'),
```

2025-01-02 19:37 UTC, nemesifier commented on docs/user/settings.rst
> +``OPENWISP_MONITORING_AUTO_WIFI_CLIENT_CHECK``
I think we should use "clients" (plural) instead of client in all references to this feature.

2025-01-02 19:37 UTC, nemesifier commented on openwisp_monitoring/monitoring/configuration.py
> +    'max_wifi_clients': {
```suggestion
    '¡wifi_clients_max': {
```

2025-01-02 19:37 UTC, nemesifier commented on openwisp_monitoring/monitoring/configuration.py
> +        'label': _('Max WiFi Clients'),
```suggestion
        'label': _('WiFi Clients (Maximum)'),
```

2025-01-02 19:37 UTC, nemesifier commented on openwisp_monitoring/monitoring/configuration.py
> +        'key': 'max_wifi_clients',
```suggestion
        'key': 'wifi_clients_max',
```

2025-01-02 19:37 UTC, nemesifier commented on openwisp_monitoring/monitoring/configuration.py
> +    'min_wifi_clients': {
```suggestion
    'wifi_clients_min': {
```

2025-01-02 19:37 UTC, nemesifier commented on openwisp_monitoring/monitoring/configuration.py
> +        'label': _('Min WiFi Clients'),
similar change here as for max

2025-01-02 19:37 UTC, nemesifier commented on openwisp_monitoring/monitoring/configuration.py
> +        'key': 'min_wifi_clients',
similar change here as for max

2025-01-02 19:37 UTC, nemesifier commented on openwisp_monitoring/monitoring/configuration.py
> +        'alert_settings': {'operator': '<', 'threshold': 0, 'tolerance': 240},
```suggestion
        'alert_settings': {'operator': '<', 'threshold': 1, 'tolerance': 1440},
```

Shouldn't this be less than 1? Would less than zero trigger at all?

I would set a tolerance of 3 days by default (4320 minutes), which would indicate an AP hasn't been used for 3 days in a row, which would account for a full weekend plus festive day, a common occurrence in many countries.

2025-01-02 19:37 UTC, nemesifier commented on openwisp_monitoring/monitoring/configuration.py
> +        'alert_settings': {'operator': '>', 'threshold': 40, 'tolerance': 60},
```suggestion
        'alert_settings': {'operator': '>', 'threshold': 50, 'tolerance': 120},
```

2025-01-08 14:59 UTC, nemesifier requested changes

2025-01-08 14:59 UTC, nemesifier commented on openwisp_monitoring/check/classes/wifi_clients.py
> +            fields='COUNT(DISTINCT(clients))',
As discussed, please move the influxdb query language details to the timeseries DB backend.

2025-01-08 14:59 UTC, nemesifier commented on openwisp_monitoring/check/classes/wifi_clients.py
> +            since="'{}'".format(
same here

2025-01-09 14:03 UTC, pandafy commented on openwisp_monitoring/monitoring/base/models.py
> +                since=timezone.now() - timedelta(minutes=self._tolerance_search_range),
Before this change, the code was iterating though points that was beyond the tolerance search range because of the broken InfluxQL query (`time >= 15m`).

2025-01-24 16:00 UTC, nemesifier reviewed
LGTM! Testing it and waiting for more feedback.

2025-01-28 18:52 UTC, nemesifier requested changes

2025-01-28 18:52 UTC, nemesifier commented on docs/user/settings.rst
> +client threshold.
I think this sentence is not really human friendly.

I think we should explain that we look for clients which have connected between now and the interval of minutes specified there of something like that.

2025-01-28 18:52 UTC, nemesifier commented on docs/user/settings.rst
> +clients threshold.
Same here and we can spend a few words on why this is a lot higher.

2025-01-29 18:19 UTC, nemesifier reviewed
Looking better, let's continue testing a bit more!

2025-02-11 20:58 UTC, nemesifier commented on docs/user/checks.rst
> +.. _wifi_clients_check:
I don't love the order of these settings in this page but I'll handle this in a separate commit as I believe you're just following what was done before which in retrospective doesn't seem the best (eg: showing iperf3 settings before other settings which are more important).

2025-02-11 21:03 UTC, merged